'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { FileText, AlertCircle, Sparkles, UserCheck } from 'lucide-react';
import styles from '../legal.module.css';

export default function TermsOfServicePage() {
  return (
    <div className={styles.container}>
      <motion.h1
        className={styles.title}
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
      >
        Terms of Service
      </motion.h1>

      <motion.p
        className={styles.subtitle}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.1 }}
      >
        Guidelines, entertainment disclaimers, and user terms for ZodiacSense.
      </motion.p>

      <motion.div
        className={styles.card}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
      >
        <h2>
          <AlertCircle size={20} />
          1. Astrological &amp; AI Disclaimer
        </h2>
        <p>
          All birth chart analysis, palm line interpretations, and cosmic compatibility readings generated by ZodiacSense are provided for <strong>personal insight, reflection, and entertainment purposes only</strong>.
        </p>
        <ul>
          <li>Readings should never replace professional medical, legal, financial, or psychological advice.</li>
          <li>Astrological forecasts are interpretive and should not be treated as absolute guarantees of future events.</li>
        </ul>

        <h2>
          <UserCheck size={20} />
          2. User Account Guidelines
        </h2>
        <p>
          By creating an account on ZodiacSense, you agree to:
        </p>
        <ul>
          <li>Provide accurate birth information for exact calculations.</li>
          <li>Maintain the confidentiality of your account credentials.</li>
          <li>Not misuse the daily AI quota through automated scraping or abusive request loops.</li>
        </ul>

        <h2>
          <Sparkles size={20} />
          3. Daily AI Quota Policy
        </h2>
        <p>
          To maintain high availability and performance for all users, ZodiacSense enforces daily quota limits per account for AI features. Quotas automatically reset every 24 hours.
        </p>

        <h2>
          <FileText size={20} />
          4. Changes to Terms
        </h2>
        <p>
          We reserve the right to update these terms at any time. Continued use of ZodiacSense following updates constitutes acceptance of the modified terms.
        </p>

        <div className={styles.lastUpdated}>
          Last Updated: August 2026 • ZodiacSense Legal Team
        </div>
      </motion.div>
    </div>
  );
}
